### ISSUE TITLE
AttributeError: 'Connection' object has no attribute 'contextual_connect'

### ISSUE THREAD

**Issue by shree14** [sqlalchemy-redshift/sqlalchemy-redshift#216] opened 2021-04-30 13:33 UTC
I'm trying to do `metadata.reflect`, here is my code:
```
from sqlalchemy import create_engine, MetaData
from os import getenv

db_uri = getenv('DATABASE_URI')

engine = create_engine(db_uri)

metadata = MetaData(engine)

metadata.reflect(bind=engine, schema='public')
```

The url format I follow is:
`redshift+psycopg2://user:passwd@host.amazonaws.com:5439/database`

I get the following error after the `metadata.reflect` statement:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4715, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 600, in __new__
    metadata._remove_table(name, schema)
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 595, in __new__
    table._init(name, metadata, *args, **kw)
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 670, in _init
    self._autoload(
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 705, in _autoload
    conn_insp.reflect_table(
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 757, in reflect_table
    tbl_opts = self.get_table_options(
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 398, in get_table_options
    return self.dialect.get_table_options(
  File "<string>", line 2, in get_table_options
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy_redshift/dialect.py", line 607, in get_table_options
    columns = self._get_redshift_columns(connection, table_name,
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy_redshift/dialect.py", line 697, in _get_redshift_columns
    all_columns = self._get_all_column_info(connection,
  File "<string>", line 2, in _get_all_column_info
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "//anaconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy_redshift/dialect.py", line 747, in _get_all_column_info
    with connection.contextual_connect() as cc:
AttributeError: 'Connection' object has no attribute 'contextual_connect'
```

Python version is `3.8.8` and versions of the packages are:

```
alembic==1.5.8
psycopg2-binary==2.8.6
SQLAlchemy==1.4.4
sqlalchemy-redshift==0.8.2
```

Any help is appreciated! Thank you!

**Comment by gboysko** [comment] 2021-05-10 18:51
FWIW, it seems like the problem is an explicit setting of the schema name. I'm having to use this to use a non-default schema name. Is there any workaround? I tried to test with older versions of `sqlalchemy-redshift`, but no luck so far.

**Comment by gboysko** [comment] 2021-05-10 20:02
Sorry, I should have tried this first. Yes, if I downgrade to `1.3`, then the problem goes away. I will use that in the mean time...

Thanks!

**Comment by jklukas** [comment] 2021-05-10 20:06
I'm going to close this as a dupe in favor of #214.

**Closed by jklukas** 2021-05-10 20:06 UTC
Labels: duplicate
