### ISSUE TITLE
Dialect cannot work with huge data tables (allocation of memory on server/client)

### ISSUE THREAD

**Issue by Rustem** [sqlalchemy-redshift/sqlalchemy-redshift#116] opened 2017-05-04 07:28 UTC
1.  For Amazon Redshift SQLAlchemy library by default using psycopg2 library that is used for Postgres. It by default using client side cursors. When sql query is executing it allocated all QuerySet in memory, because of this big query is overflow memory limit.
After this I tried to use Raw Driver Connection using Psycopg2 and work with server side cursor that is recommended by psycopg documentation (http://initd.org/psycopg/docs/usage.html#server-side-cursors):
http://docs.aws.amazon.com/redshift/latest/dg/declare.html
```sql
begin;
DECLARE curname cursor FOR
    SELECT * FROM schema.table;
fetch forward 10 from curname;
fetch next from curname;
close curname;
commit;
```
or
```python
command_text = """
    SELECT * FROM schema.table;
"""
conn = psycopg2.connect(host="HOST", dbname="dbname", password="****", user="user", port="5439")
cursor2 = conn.cursor('curname')
cursor2.itersize = 100
cursor2.execute(command_text)
for item in cursor2:
    print(item)
```
This method is executed but it still allocated all queryset on server side and executing for about 10 minutes. In same cases it still have problem with overflow memory, but at this time on server side.

2. When I tried to execute it using SQL Workbench query is starting executing and return result in loop by 1000 result and printed it.
I assuming that workbench is making another kind of limit offset on their side.
Also I tested it using java code and use redhift jdbc driver using Java. It code work as expected and return result row by row.
So I assuming problem in python driver psycopg2 that allocating queryset in memory before returning result
```java
package connection;

import java.sql.*;
import java.util.Properties;
public class Redshift {
    //Redshift driver: "jdbc:redshift://host:5439/dev";
    static final String dbURL = "jdbc:redshift://host:5439/dbname";
    static final String MasterUsername = "user";
    static final String MasterUserPassword = "****";
    public static void main(String[] args) {
        Connection conn = null;
        Statement stmt = null;
        try{
           Class.forName("com.amazon.redshift.jdbc41.Driver");
           //Open a connection and define properties.
           System.out.println("Connecting to database...");
           Properties props = new Properties();
           //Uncomment the following line if using a keystore.
           //props.setProperty("ssl", "true");
           props.setProperty("user", MasterUsername);
           props.setProperty("password", MasterUserPassword);
           conn = DriverManager.getConnection(dbURL, props);
           //Try a simple query.
           System.out.println("Listing system tables...");
           stmt = conn.createStatement();
           String sql;
           sql = "SELECT * FROM schema.table;";
           ResultSet rs = stmt.executeQuery(sql);
           //Get the data from the result set.
           while(rs.next()){
              //Retrieve two columns.
              String catalog = rs.getString("list_entry_id");
              String name = rs.getString("source_code");
              //Display values.
              System.out.print("Catalog: " + catalog);
              System.out.println(", Name: " + name);
           }
           rs.close();
           stmt.close();
           conn.close();
        }catch(Exception ex){
           //For convenience, handle all errors here.
           ex.printStackTrace();
        }finally{
           //Finally block to close resources.
           try{
              if(stmt!=null)
                 stmt.close();
           }catch(Exception ex){
           }// nothing we can do
           try{
              if(conn!=null)
                 conn.close();
           }catch(Exception ex){
              ex.printStackTrace();
           }
        }
        System.out.println("Finished connectivity test.");
     }
}
```

**Comment by jklukas** [comment] 2017-05-04 12:33
From this description, it sounds like the issue is at the psycopg2 layer rather than with sqlalchemy-redshift. If you can configure psycopg2 to have reasonable behavior for your case, we can likely figure out how to expose that through sqlalchemy, but if it's a psycopg2 limitation, that would need to be addressed upstream.

**Comment by graingert** [comment] 2017-05-04 12:47
sounds like issue #100 to me

**Comment by Rustem** [comment] 2017-05-05 17:27
@graingert really seems abnormal behaviour for the cursors. I can't go to production with python app due to this bug.

**Comment by graingert** [comment] 2017-05-05 19:33
This is psycopg2's default behaviour. Can you show a way of using streaming
cursors with pure psycopg2?

**Comment by Rustem** [comment] 2017-05-07 18:52
I will answer asap thanks

**Comment by Rustem** [comment] 2017-05-08 14:22
@graingert for redshift connection I tried both:
1) raw SQL commands
```
begin;
DECLARE curname cursor FOR
    SELECT * FROM schema.table;
fetch forward 10 from curname;
fetch next from curname;
close curname;
commit;
```

**Comment by graingert** [comment] 2017-05-08 15:05
@Rustem sorry it's not clear what you mean, when you use part 2 (using curname) does it run without taking up all your memory?

How about when using `.execution_options(stream_results=True)` ?

```python
@Profiler.profile
def test_core_fetchmany_w_streaming(n):
    """Load Core result rows using fetchmany/streaming."""

    with engine.connect() as conn:
        result = conn.execution_options(stream_results=True).\
            execute(Customer.__table__.select().limit(n))
        while True:
            chunk = result.fetchmany(10000)
            if not chunk:
                break
            for row in chunk:
                data = row['id'], row['name'], row['description']
```

**Comment by Rustem** [comment] 2017-05-08 17:20
I think i tried this one, I will try it again and share my results here.

**Comment by graingert** [comment] 2017-05-08 17:21
@Rustem when you use part 2 (psycopg2, using curname) does it run without taking up all your memory?

**Comment by Rustem** [comment] 2017-05-09 06:37
It works for postgres @graingert , I am trying to do it with redshift now

**Comment by Rustem** [comment] 2017-05-09 07:33
I am looking through the code of dialect and see that exec option called `stream_results` just reuses psycopg2 cursor. They way it should work is to use the native cursor SQL commands. Seems psycopg2 uses https://www.postgresql.org/docs/9.2/static/plpgsql-cursors.html, but redshift cursors has different syntax to operate over it. As soon as  I will profile on the redshift i update my comment

**Comment by Rustem** [comment] 2017-05-09 07:53
btw, why don't u try something like redshift-odbc ?

**Comment by Rustem** [comment] 2017-05-09 09:58
So it does not work for now with 600 million records it is too long. 
So this picture on AWS is for minutes and nothing get updated. 
![profiling_redshift_1](https://cloud.githubusercontent.com/assets/195228/25845612/5fe1e824-34d0-11e7-97aa-10f266beab70.jpeg)

**Comment by graingert** [comment] 2017-05-09 10:11
@Rustem when you use part 2 (psycopg2, using curname) does it run without taking up all your memory?

**Comment by Rustem** [comment] 2017-05-09 10:25
@graingert no same situation. It allocates memory on server

**Comment by graingert** [comment] 2017-05-09 10:26
> memory on server

on the server or the client?

**Comment by Rustem** [comment] 2017-05-09 10:28
@graingert on the server

**Comment by Rustem** [comment] 2017-05-09 10:28
It will raise clientside if u use basic cursor.

**Comment by Rustem** [comment] 2017-05-09 10:32
However when I test with JDBC connection (pure Java code), then everything works fine and I observe that it does not use cursors, it just uses pure stream. According to the server query log, I see only `SELECT * FROM lineorder`, but console feed data immediately.

**Comment by graingert** [comment] 2017-05-09 10:45
@Rustem I'm not interested in Java code. Can you demonstrate Python code that would not trigger the issue you're having. If not, it's not an issue in sqlalchemy-redshift.

**Comment by Rustem** [comment] 2017-05-09 10:52
@graingert then may be you show to me a working code that could execute cursor on the huge tables. I think i will raise the issue on psycopg2 https://github.com/psycopg/psycopg2/issues/new

**Comment by graingert** [comment] 2017-05-09 13:50
> then may be you show to me a working code that could execute cursor on the huge tables.

This project has very little to do with raw psycopg2 interaction. It's just used to generate the SQL from generic(-ish) sqlalchemy expressions

**Comment by graingert** [comment] 2017-05-09 13:51
closing in favour of https://github.com/psycopg/psycopg2/issues/553

**Closed by graingert** 2017-05-09 13:50 UTC
