### ISSUE TITLE
Any way to support sqlalchemy >= 2.0?

### ISSUE THREAD

**Issue by playermanny2** [sqlalchemy-redshift/sqlalchemy-redshift#295] opened 2023-12-04 18:30 UTC
https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/a077110366a3c451f1c41b2fa56f6e3cd5c438dd/setup.py#L24

Hey -- due to some changes in how langchain requires sql alchemy > 2.0 and thise requires < 2.0 , i'm wondering on if it's possible to upgrade this module to support 2.0
I am currently reading data from redshift, but also using that in conjunction with langchain to perform other LLM caabilities (more notably the semantic caching layer which is causing issues)

**Comment by playermanny2** [comment] 2023-12-04 18:31
closing as it's duplicate of #264

**Comment by maoxingda** [comment] 2024-01-07 13:49
Is this code repository still under maintenance?

**Comment by Brooke-white** [comment] 2024-01-08 21:19
this is a dupe of #264, so closing. we are evaluating roadmap plans for 2024 and I'm requesting this feature to be prioritized. I'll update in #264 once we have a decision.

**Closed as completed by Brooke-white** 2024-01-08 21:19 UTC
